using DrunkSquad.Database;
using DrunkSquad.Database.Accessors;
using DrunkSquad.Logic.Users.Login;
using DrunkSquad.Logic.Users.Registration;
using DrunkSquad.Models.Config;
using DrunkSquad.Models.Users;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using TornApi.Net.Models.Common;
using TornApi.Net.Models.Faction;
using TornApi.Net.Models.User;
using TornApi.Net.REST;

var builder = WebApplication.CreateBuilder (args);

// Add services to the container.
builder.Services.AddControllersWithViews ();

AddServices (builder);
AddEntityAccessors (builder);

// Auto generated by ChatGPT
builder.Services.AddDbContext<DrunkSquadDBContext> ((provider, options) => {
    WebsiteConfig websiteConfig = (WebsiteConfig) provider.GetRequiredService<IWebsiteConfig> ();

    options.UseNpgsql (websiteConfig.GetConnectionString ("Local"));
});

var app = builder.Build ();


// Configure the HTTP request pipeline.
if (!app.Environment.IsDevelopment ()) {
    app.UseExceptionHandler ("/Home/Error");
    // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
    app.UseHsts ();
}

app.UseHttpsRedirection ();
app.UseStaticFiles ();

app.UseRouting ();

app.UseAuthorization ();

app.MapControllerRoute (
    name: "default",
    pattern: "{controller=Home}/{action=Index}/{id?}");

app.Run ();

void AddServices (WebApplicationBuilder builder) {
    IServiceCollection services = builder.Services;

    services.AddSingleton<IConfiguration> (builder.Configuration);
    services.AddSingleton<IWebsiteConfig, WebsiteConfig>((services) => new WebsiteConfig (services.GetService<IConfiguration> ()));

    services.AddSingleton<IHttpClientFactory> (DefaultApiRequestClientFactory.Instance);

    services.AddScoped<IPasswordHasher<LoginDetails>, PasswordHasher<LoginDetails>>();

    services.AddScoped<ILoginHandler, LoginHandler> ();
    services.AddScoped<IRegistrationHandler, RegistrationHandler> ();

    services.AddAuthentication (CookieAuthenticationDefaults.AuthenticationScheme)
            .AddCookie (options => {
                options.ExpireTimeSpan = TimeSpan.FromMinutes (20);
                options.SlidingExpiration = true;
                options.AccessDeniedPath = "/Login/Login";
            });
}

void AddEntityAccessors (WebApplicationBuilder builder) {
    IServiceCollection services = builder.Services;

    services.AddSingleton<IUserAccess, UserAccess> (services => {
        var context = services.GetService<DrunkSquadDBContext> ();
        var set = context.Users;

        return new UserAccess (set, context);
    });

    services.AddSingleton<IJobAccess, JobAccess> (services => {
        var context = services.GetService<DrunkSquadDBContext> ();
        var set = context.Set<Job> ();

        return new JobAccess (set, context);
    });

    services.AddSingleton<ILastActionAccess, LastActionAccess> (services => {
        var context = services.GetService<DrunkSquadDBContext> ();
        var set = context.Set<LastAction> ();

        return new LastActionAccess (set, context);
    });

    services.AddSingleton<IMarriageAccess, MarriageAccess> (services => {
        var context = services.GetService<DrunkSquadDBContext> ();
        var set = context.Set<Marriage> ();

        return new MarriageAccess (set, context);
    });

    services.AddSingleton<IPlayerStatesAccess, PlayerStatesAccess> (services => {
        var context = services.GetService<DrunkSquadDBContext> ();
        var set = context.Set<PlayerStates> ();

        return new PlayerStatesAccess (set, context);
    });

    services.AddSingleton<IStatusAccess, StatusAccess> (services => {
        var context = services.GetService<DrunkSquadDBContext> ();
        var set = context.Set<Status> ();

        return new StatusAccess (set, context);
    });

    services.AddSingleton<IFactionStubAccess, FactionStubAccess> (services => {
        var context = services.GetService<DrunkSquadDBContext> ();
        var set = context.Set<FactionStub> ();

        return new FactionStubAccess (set, context);
    });

    services.AddSingleton<ILoginDetailsAccess, LoginDetailsAccess> (services => {
        var context = services.GetService<DrunkSquadDBContext> ();
        var set = context.Set<LoginDetails> ();

        return new LoginDetailsAccess (set, context);
    });

    services.AddSingleton<IMemberAccess, MemberAccess> (services => {
        var context = services.GetService<DrunkSquadDBContext> ();
        var set = context.Set<Member> ();

        return new MemberAccess (set, context);
    });

    services.AddSingleton<ICrimeAccess, CrimeAccess> (services => {
        var context = services.GetService<DrunkSquadDBContext> ();
        var set = context.Set<Crime> ();

        return new CrimeAccess (set, context);
    });

}